version: '3.1'

services:

  api:
    container_name: api
    image: maven:3.6.0-jdk-11-slim
    ports:
      - 8080:8080
    depends_on:
      - db
    working_dir: /usr/app/api
    volumes:
      - ./src:/usr/app/api/src
      - ./pom.xml:/usr/app/api/pom.xml
      - ./.mvn:/usr/app/api/.mvn
      - ./mvnw:/usr/app/api/mvnw
      - api_lib:/usr/app/api/lib
    command: sh -c "mvn spring-boot:run"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: iuGIuy65dai7a6dagfd
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/moviecatalog?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true

  db:
    container_name: db
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: iuGIuy65dai7a6dagfd

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: node:lts-alpine
    volumes:
      - ./src/main/frontend:/usr/app/front
      - frontend_node_modules:/usr/app/front/node_modules
    working_dir: /usr/app/front
    restart: on-failure
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000

volumes:
  api_lib:
  frontend_node_modules:
